local description = 
[[Clean project files generated by Premake5
-----
Options:
-A|-all - Clean both project and build files
-b|-build - Clean the entire build
-E|-Engine|-engine - Clean Engine project
-e|-editor - Clean Editor project
-h|-help - Shows clean options
-t|-test - Clean Test project
-s|-self - Clean all non-external projects]]

newaction {
    trigger = "clean",
    description = description,
    execute = function()

        -- No args
        if (_ARGS[1] == nil) then
            print("Cleaning Generated")
            os.rmdir("./Generated")
            return
        end

        local index = 1;
        while (_ARGS[index] ~= nil) do
            local arg = _ARGS[index]

            if (arg == "-A" or arg == "-all") then
                print("Cleaning All")

                os.execute("{RMDIR} ./Generated")
                os.execute("{RMDIR} ./Build")

            elseif (arg == "-b" or arg == "--build") then
                print("Cleaning Build")

                os.rmdir("./Build")

            elseif (arg == "-E" or arg == "-Engine" or arg == "-engine") then
                print("Cleaning Engine")
                
                os.execute("{RMDIR} ./Build/Obj/Engine/")
                os.execute("{RMDIR} ./Build/Target/Engine/")
                os.remove("./Generated/Engine.vcxproj")
                os.remove("./Generated/Engine.vcxproj.filters")

            elseif (arg == "-e" or arg == "-editor") then
                print("Cleaning Editor")
                
                os.execute("{RMDIR} ./Build/Obj/Editor/")
                os.execute("{RMDIR} ./Build/Target/Editor/")
                os.remove("./Generated/Editor.vcxproj")
                os.remove("./Generated/Editor.vcxproj.filters")

            elseif (arg == "-h" or arg == "-help") then
                print(description)

            elseif (arg == "-t" or arg == "-test") then
                print("Cleaning Test")

                os.execute("{RMDIR} ./Build/Obj/Test/")
                os.execute("{RMDIR} ./Build/Target/Test/")
                os.remove("./Generated/Test.vcxproj")
                os.remove("./Generated/Test.vcxproj.filters")

            elseif (arg == "-s" or arg == "-self") then
                print("Cleaning Self")
                
                -- Engine
                os.execute("{RMDIR} ./Build/Obj/Engine/")
                os.execute("{RMDIR} ./Build/Target/Engine/")
                os.remove("./Generated/Engine.vcxproj")
                os.remove("./Generated/Engine.vcxproj.filters")

                -- Editor
                os.execute("{RMDIR} ./Build/Obj/Editor/")
                os.execute("{RMDIR} ./Build/Target/Editor/")
                os.remove("./Generated/Editor.vcxproj")
                os.remove("./Generated/Editor.vcxproj.filters")

                -- Test
                os.execute("{RMDIR} ./Build/Obj/Test/")
                os.execute("{RMDIR} ./Build/Target/Test/")
                os.remove("./Generated/Test.vcxproj")
                os.remove("./Generated/Test.vcxproj.filters")

            else
                print([[Invalid option entered. "Premake5 clean -h" to show all clean options]])
            end

            index = index + 1
        end
    end
}