#include "UniformBuffer.hpp"
#include "BufferHelper.hpp"
#include <chrono>

//The perspective projection matrix generated by GLM will use the OpenGL depth range of -1.0 to 1.0 by default. 
//We need to configure it to use the Vulkan range of 0.0 to 1.0 using the GLM_FORCE_DEPTH_ZERO_TO_ONE definition.
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#include <glm/gtc/matrix_transform.hpp>

using namespace Droplet::Graphics::VK;

UniformBuffer::UniformBuffer(vk::raii::Device const &p_device, 
							 vk::raii::PhysicalDevice const &p_physDevice)
{
	vk::DeviceSize bufferSize = sizeof(UniformBufferObject);
	auto [buffer, memory] = CreateBuffer(p_device, p_physDevice, 
		bufferSize, 
		vk::BufferUsageFlagBits::eUniformBuffer, 
		vk::MemoryPropertyFlagBits::eHostVisible | vk::MemoryPropertyFlagBits::eHostCoherent);

	m_uniformBuffer = std::move(buffer);
	m_deviceMemory = std::move(memory);
	m_mappedBuffer = m_deviceMemory.mapMemory(0, bufferSize);
}

void UniformBuffer::UpdateBuffer(const vk::Extent2D &p_swapchainExtent)
{
	static auto s_startTime = std::chrono::high_resolution_clock::now();

	auto  _currentTime = std::chrono::high_resolution_clock::now();
	float _time = std::chrono::duration<float>(_currentTime - s_startTime).count();

	UniformBufferObject ubo{};
	ubo.model = rotate(glm::mat4(1.0f), _time * glm::radians(90.0f), glm::vec3(0.0f, 0.0f, 1.0f));
	ubo.view = lookAt(glm::vec3(2.0f, 2.0f, 2.0f), glm::vec3(0.0f, 0.0f, 0.0f), glm::vec3(0.0f, 0.0f, 1.0f));
	ubo.proj =
		glm::perspective(glm::radians(45.0f), static_cast<float>(p_swapchainExtent.width) / static_cast<float>(p_swapchainExtent.height), 0.1f, 10.0f);

	memcpy(m_mappedBuffer, &ubo, sizeof(ubo));
}