#include "UniformBuffer.hpp"
#include "BufferHelper.hpp"
#include <chrono>

#include <vk_mem_alloc_raii.hpp>

//The perspective projection matrix generated by GLM will use the OpenGL depth range of -1.0 to 1.0 by default. 
//We need to configure it to use the Vulkan range of 0.0 to 1.0 using the GLM_FORCE_DEPTH_ZERO_TO_ONE definition.
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#include <glm/gtc/matrix_transform.hpp>
#undef GLM_FORCE_DEPTH_ZERO_TO_ONE

using namespace Droplet::Graphics::VK;

UniformBuffer::UniformBuffer(const vma::raii::Allocator &p_allocator)
{
	vk::BufferCreateInfo bufferCreateInfo
	{
		.size = sizeof UniformBufferObject, 
		.usage = vk::BufferUsageFlagBits::eUniformBuffer,
		.sharingMode = vk::SharingMode::eExclusive
	};

	vma::AllocationCreateInfo allocCreateInfo
	{
		.flags = vma::AllocationCreateFlagBits::eHostAccessRandom,
		.usage = vma::MemoryUsage::eAuto,
		.requiredFlags = vk::MemoryPropertyFlagBits::eHostVisible | vk::MemoryPropertyFlagBits::eHostCoherent,
	};
	
	m_buffer = vma::raii::Buffer{p_allocator, bufferCreateInfo, allocCreateInfo};
}

void UniformBuffer::UpdateBuffer(const vk::Extent2D &p_swapchainExtent) const
{
	typedef std::chrono::time_point<std::chrono::steady_clock> TimePoint;
	
	static TimePoint s_startTime { std::chrono::high_resolution_clock::now() };
	const TimePoint  currentTime { std::chrono::high_resolution_clock::now() };
	const float time = { std::chrono::duration<float>(currentTime - s_startTime).count() };

	const UniformBufferObject ubo
	{
		.model = rotate(glm::mat4(1.0f), time * glm::radians(90.0f), glm::vec3(0.0f, 0.0f, 1.0f)),
		.view = lookAt(glm::vec3(2.0f, 2.0f, 2.0f), glm::vec3(0.0f, 0.0f, 0.0f), glm::vec3(0.0f, 0.0f, 1.0f)),
		.proj = glm::perspective(glm::radians(45.0f), static_cast<float>(p_swapchainExtent.width) / static_cast<float>(p_swapchainExtent.height), 0.1f, 10.0f)
	};
	
	vma::AllocationInfo allocInfo = m_buffer.getAllocation().getInfo(); 

	std::memcpy(allocInfo.pMappedData, &ubo, sizeof(ubo));
}
