#include "UniformBuffer.hpp"
#include "BufferHelper.hpp"
#include <chrono>

//The perspective projection matrix generated by GLM will use the OpenGL depth range of -1.0 to 1.0 by default. 
//We need to configure it to use the Vulkan range of 0.0 to 1.0 using the GLM_FORCE_DEPTH_ZERO_TO_ONE definition.
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#include <glm/gtc/matrix_transform.hpp>

using namespace Droplet::Graphics::VK;

UniformBuffer::UniformBuffer(vk::raii::Device const &p_device, 
							 vk::raii::PhysicalDevice const &p_physDevice)
{
	constexpr vk::DeviceSize bufferSize = sizeof(UniformBufferObject);
	
	vk::raii::Buffer buffer {nullptr};
	vk::raii::DeviceMemory memory {nullptr};
	std::tie(buffer, memory) = CreateBuffer
	(
		p_device,
		p_physDevice, 
		bufferSize, 
		vk::BufferUsageFlagBits::eUniformBuffer, 
		vk::MemoryPropertyFlagBits::eHostVisible | vk::MemoryPropertyFlagBits::eHostCoherent
	);

	m_uniformBuffer = std::move(buffer);
	m_deviceMemory = std::move(memory);
	m_mappedBuffer = m_deviceMemory.mapMemory(0, bufferSize);
}

void UniformBuffer::UpdateBuffer(const vk::Extent2D &p_swapchainExtent) const
{
	typedef std::chrono::time_point<std::chrono::steady_clock> TimePoint;
	
	static TimePoint s_startTime { std::chrono::high_resolution_clock::now() };
	const TimePoint  currentTime { std::chrono::high_resolution_clock::now() };
	const float time = { std::chrono::duration<float>(currentTime - s_startTime).count() };

	const UniformBufferObject ubo
	{
		.model = rotate(glm::mat4(1.0f), time * glm::radians(90.0f), glm::vec3(0.0f, 0.0f, 1.0f)),
		.view = lookAt(glm::vec3(2.0f, 2.0f, 2.0f), glm::vec3(0.0f, 0.0f, 0.0f), glm::vec3(0.0f, 0.0f, 1.0f)),
		.proj = glm::perspective(glm::radians(45.0f), static_cast<float>(p_swapchainExtent.width) / static_cast<float>(p_swapchainExtent.height), 0.1f, 10.0f)
	};

	std::memcpy(m_mappedBuffer, &ubo, sizeof(ubo));
}
